default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ChallengeAlkemy_development
  username: ChallengeAlkemy_development
  password: password

test:
  <<: *default
  database: ChallengeAlkemy_test
  username: ChallengeAlkemy_test
  password: password


production:
  <<: *default
  database: ChallengeAlkemy_production
  username: ChallengeAlkemy
  password: <%= ENV['CHALLENGEALKEMY_DATABASE_PASSWORD'] %>
